#!/bin/bash

# If we run under tmux/screen do nothing.
if [[ $TERM == screen* ]]; then
  echo "Do not run `basename $0` under tmux/screen"
  exit 1
fi

# TMUX options
TO="-2 -u"

# Get number of running tmux sessions
tmux_sessions=`tmux ls 2> /dev/null | wc -l`

if [ "$#" == "0" ] ; then
  if [ "$tmux_sessions" == "0" ] ; then
    # Start new standard session
    tmux $TO start \; source $HOME/.tmux/std.tmux \; attach-session -t mips
  elif [ "$tmux_sessions" == "1" ] ; then
    # Attach to the only running session
    tmux $TO attach-session
  else
    echo "Running sessions (tmux attach-session -t #):"
    echo "--------------------------------------------"
    tmux $TO ls
  fi
else
  tmux $TO $@
fi
